---
language: bash

dist: trusty

env:
  - VERSION=9.0-2.1
  - VERSION=9.1-2.1
  - VERSION=9.2-2.1
  - VERSION=9.3-2.1
  - VERSION=9.4-2.1

install:
  - git clone -b additional-test-config https://github.com/appropriate/docker-library-official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION"
  - image="appropriate/postgis:$VERSION"

script:
  - docker build --pull -t "$image" .
  - ~/official-images/test/run.sh -c ~/official-images/test/config.sh -c ../test/postgis-config.sh "$image"
