version: '3'
services:
  db:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: postgre_container
    environment:
      POSTGRES_DB: postgre
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    volumes:
      - ../pg_data:/var/lib/postgresql/data
      - ../sql:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
  qgis:
    container_name: qgis_container
    image: qgis/qgis
    environment:
      DISPLAY: ${DISPLAY}
    ports:
      - 8080:80
    links:
      - db:db
    